#!/bin/bash

# install script --> detect the OS and install all the necessary goodies

# colors for printing
RED='\033[1;31m'
GREEN='\033[1;32m'
BLUE='\033[1;36m'
NC='\033[0m' # No Color

DEBUG=0

if [[ DEBUG -gt 0 ]];
then
	echo -e "	${RED}DEBUG mode${NC}"
fi

# do something with a dramatic effect
dramatic_effect() {
	echo -n "Detecting your OS"
	for (( i=0; i<3; i++ ))
	do
			sleep $1
			echo -n "."
	done
	echo
}

dramatic_effect 0.5

if [[ "$OSTYPE" == "linux-gnu"* ]];
then
	echo -e "	OS --> ${BLUE}$OSTYPE${NC}"
	echo -e "🍬  Installing the goodies"

	sudo apt update

	# get gcc and tools and add manpages for gcc
	sudo apt install build-essential
	sudo apt-get install manpages-dev

	# some misc stuff
	sudo apt install curl
	sudo apt install vim
	sudo apt install tmux
	
	# install visual studio code
	sudo snap install --classic code

	# install Java
	sudo apt install default-jre

	# insall zsh and make it default shell then install oh-my-zsh
	sudo apt install zsh
	chsh -s $(which zsh)
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

elif [[ "$OSTYPE" == "darwin"* ]];
then
	echo -e "	OS --> ${BLUE}$OSTYPE${NC}"
	if [[ DEBUG -gt 0 ]];
	then
		echo "debug mode"
		echo -e "🍬  Installing the goodies"
	
	else
		echo -e "🍬  Installing the goodies"

		# install homebrew
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		# run the brew file to install all the goodies
		brew bundle
	fi

else
	# if we're here then you got a job that probably requires windows...womp womp
	echo -e "${RED}$OSTYPE${NC} is not supported...womp womp"
	echo "exiting..."
	exit 1
fi

if [[ ! DEBUG ]];
then
	# create the symlinks for the config files
	ln -sfn ~/projects/dotfiles/.zshrc ~
	ln -sfn ~/projects/dotfiles/.vimrc ~
	ln -sfn ~/projects/dotfiles/.tmux.conf ~

	# install vim-fugitive git wrapper for vim
	mkdir -p ~/.vim/pack/tpope/start
	cd ~/.vim/pack/tpope/start
	git clone https://tpope.io/vim/fugitive.git
	vim -u NONE -c "helptags fugitive/doc" -c q
fi
