#!/bin/bash

# all the stuff for linux

sudo apt update

# install home brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# get homebrew on PATH

# get gcc and tools and manpages for gcc
sudo apt install build-essential
sudo apt-get install manpages-dev

# some misc stuff
sudo apt-get install git
sudo apt install curl
sudo apt install vim
sudo apt install tmux
apt-get install silversearcher-ag
sudo apt-get install fzf
sudo apt install bat
sudo apt-get install ripgrep
sudo apt install fd-find
ln -s $(which fdfind) ~/.local/bin/fd


# install visual studio code
sudo snap install --classic code

# install java
sudo apt install default-jre

# install libcurl C lib
sudo apt-get install libcurl4-gnutls-dev
# valgrind memory leak checker
sudo apt-get install valgrind

# install zsh and make it default shell then install oh-my-zsh
sudo apt install zsh
chsh -s $(which zsh)

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
