#!/bin/bash

# all the stuff for linux

sudo apt update

# get gcc and tools and manpages for gcc
sudo apt install build-essential
sudo apt-get install manpages-dev

# some misc stuff
sudo apt install curl
sudo apt install vim
sudo apt install tmux

# install visual studio code
sudo snap install --classic code

# install java
sudo apt install default-jre

# install libcurl C lib
sudo apt-get install libcurl4-gnutls-dev
# valgrind memory leak checker
sudo apt-get install valgrind

# install zsh and make it default shell then install oh-my-zsh
sudo apt install zsh
chsh -s $(which zsh)

sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

